### ISSUE TITLE
Window issue with Ajax

### ISSUE THREAD

**Issue by taylorsmcclure** [rchipka/node-osmosis#141]
I am trying to make Osmosis emulate a window so some Ajax elements are loaded which will get me to the page I need to scrape. However, it appears I am getting an undefined error for cookies in Needlejs:

```
/mnt/projects/swa-dashboard/node_modules/needle/lib/cookies.js:31
  return str.toString().replace(EXCLUDED_CHARS, encodeURIComponent);
            ^

TypeError: Cannot read property 'toString' of undefined
    at encodeCookieComponent (/mnt/projects/swa-dashboard/node_modules/needle/lib/cookies.js:31:13)
    at /mnt/projects/swa-dashboard/node_modules/needle/lib/cookies.js:65:24
    at Array.reduce (native)
    at Object.writeCookieString [as write] (/mnt/projects/swa-dashboard/node_modules/needle/lib/cookies.js:63:27)
    at Needle.setup (/mnt/projects/swa-dashboard/node_modules/needle/lib/needle.js:206:40)
    at Needle.start (/mnt/projects/swa-dashboard/node_modules/needle/lib/needle.js:260:27)
    at Object.exports.request (/mnt/projects/swa-dashboard/node_modules/needle/lib/needle.js:670:56)
    at HttpRequest (/mnt/projects/swa-dashboard/node_modules/libxmljs-dom/lib/HttpRequest.js:40:12)
    at Object.__evalScripts (/mnt/projects/swa-dashboard/node_modules/libxmljs-dom/lib/Window.js:83:13)
    at /mnt/projects/swa-dashboard/node_modules/libxmljs-dom/lib/Window.js:92:24
```

I used the `.then("window")` method described in https://github.com/rchipka/node-osmosis/issues/81. Is there some param I am missing to avoid this issue? Or is this an upstream issue with needle/libxmljs-dom?

**Comment by JulianKingman** [comment]
Same problem. @taylorsmcclure did you resolve this somehow?
