### ISSUE TITLE
HTML in attribute causes osmosis to stop parsing the DOM

### ISSUE THREAD

**Issue by Swahvay** [rchipka/node-osmosis#184]
[This page](https://horsetelexresults.com/tourney/index) has a `<meta>` element whose `content` attribute includes HTML. When osmosis tries to parse the HTML, it throws these errors:
```
 { Error: AttValue: " expected
    at Object.module.exports.fromHtml (/Users/sparker/Barnlog/script/MegaScraper/node_modules/libxmljs/lib/document.js:143:21)
    at /Users/sparker/Barnlog/script/MegaScraper/node_modules/osmosis/lib/Request.js:49:31
    at done (/Users/sparker/Barnlog/script/MegaScraper/node_modules/needle/lib/needle.js:385:14)
    at PassThrough.<anonymous> (/Users/sparker/Barnlog/script/MegaScraper/node_modules/needle/lib/needle.js:598:9)
    at emitNone (events.js:110:20)
    at PassThrough.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
       domain: 5,
       code: 40,
       level: 2,
       column: 82,
       file: 'https://horsetelexresults.com/tourney/index',
       line: 44 },

     { Error: Couldn't find end of Start Tag meta
    at Object.module.exports.fromHtml (/Users/sparker/Barnlog/script/MegaScraper/node_modules/libxmljs/lib/document.js:143:21)
    at /Users/sparker/Barnlog/script/MegaScraper/node_modules/osmosis/lib/Request.js:49:31
    at done (/Users/sparker/Barnlog/script/MegaScraper/node_modules/needle/lib/needle.js:385:14)
    at PassThrough.<anonymous> (/Users/sparker/Barnlog/script/MegaScraper/node_modules/needle/lib/needle.js:598:9)
    at emitNone (events.js:110:20)
    at PassThrough.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
       domain: 5,
       code: 73,
       level: 2,
       column: 82,
       file: 'https://horsetelexresults.com/tourney/index',
       line: 44,
       str1: 'meta' } 
```
Here is the offending tag. When I log `context.doc().toString()` it stops after "International equestrian results":
```
<meta property="og:description" content="International equestrian results<br>from all over the world">
```

**Comment by rchipka** [comment]
Looks like libxml can't parse this.

The source HTML may need to be sanitized using something like HTML Tidy before it is parsed.

You'll need to do something like this:
```javascript
osmosis.config({
  process_response: function (data) {
    return HTMLTidy(data)
  }
});
```

**Comment by Swahvay** [comment]
I will give that a shot. In the meantime, when I inspect the attribute in Chrome dev console, there is also a U+FFFD character before the `<br>`. Not sure if it's really that causing the problem or if it's Chrome putting it there for its own marking sake when it parses the HTML.

**Comment by rchipka** [comment]
I got that in Firefox as well

**Comment by Swahvay** [comment]
Since HTMLTidy is asynchronous, is there a way to process the response without having to return directly? Otherwise I end up getting things like this:
```
<html url="https://horsetelexresults.com/tourney/index"><body><p>[object Promise]</p></body></html>
```

**Comment by rchipka** [comment]
I was wondering myself why I didn't make the option async.

You can try something like:

```javascript
osmosis.config({
  parse: false
})
.get(...)
.then(function (res, data, next) {
  var self = this;
  HTMLTidy(res, function (html) {
    next(self.instance.parse(html));
  });
});
