### ISSUE TITLE
"Error: socket hang up" makes `context` null so 'set' throws an error

### ISSUE THREAD

**Issue by Ivanca** [rchipka/node-osmosis#64]
```
C:\scraper\node_modules\osmosis\lib\promises.js:411
                    data.obj[key] = getContent(context.get(val));
                                                      ^

TypeError: Cannot read property 'get' of null
    at loopObject (C:\scraper\node_modules\osmosis\lib\promises.js:411:55)
    at Promise.set [as cb] (C:\scraper\node_modules\osmosis\lib\promises.js:416:9)
    at Promise.start (C:\scraper\node_modules\osmosis\lib\promise.js:227:9)
    at C:\scraper\node_modules\osmosis\lib\promise.js:217:81
    at cb (C:\scraper\node_modules\osmosis\lib\promises.js:183:17)
    at C:\scraper\node_modules\osmosis\lib\promise.js:266:5
    at C:\scraper\node_modules\osmosis\index.js:231:13
    at done (C:\scraper\node_modules\needle\lib\needle.js:357:7)
    at ClientRequest.had_error (C:\scraper\node_modules\needle\lib\needle.js:364:5)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketCloseListener (_http_client.js:241:9)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```
-------------------
I modified **promises.js:411** to check for context before using it and it seems to have fixed the issue, but I'm not sure about its correctness and implications.
```diff
-               } else {
+               } else if (context) {
                    data.obj[key] = getContent(context.get(val));
                }
```
Some times I have to check for context !== null but it is on the user-space so I guess that's Ok (e.g. not a bug)

**Comment by rc0x03** [comment]
When an HTTP request fails, osmosis shouldn't be sending a null context to the next command in the first place. This means that if there is a socket hang up, osmosis should log the error and never call `set`. Can you give more details or an example?
