### ISSUE TITLE
`then` callback can't be an arrow function

### ISSUE THREAD

**Issue by bisubus** [rchipka/node-osmosis#89]
In osmosis v1.0.0, when `then` is being fed with arrow callback

```
osmosis.get('...').then((ctx) => { ... })
```

an error is thrown

```
        contextArg = callback.toString().match(regexp_function_arg)[2];
                                                                   ^

TypeError: Cannot read property '2' of null
    at Object.module.exports.then (<...>\node_modules\osmosis\lib\commands\then.js:114:68)
    at Object.Command.(anonymous function) [as then] (<...>\node_modules\osmosis\lib\Command.js:502:28)
    at Object.<anonymous> (<...>\index.js:44:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
```

**Comment by rchipka** [comment]
Fixed in 1.0.1
